Search.appendIndex(
    [
                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum",
            "name": "BaseEnum",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#method___construct"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003A_fromGetter\u0028\u0029",
            "name": "_fromGetter",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#method__fromGetter"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003A_create\u0028\u0029",
            "name": "_create",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#method__create"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003AfromValue\u0028\u0029",
            "name": "fromValue",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#method_fromValue"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003AfromName\u0028\u0029",
            "name": "fromName",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#method_fromName"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#method_getValue"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#method_getName"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003A\u0024_instancedValues",
            "name": "_instancedValues",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#property__instancedValues"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003A\u0024_value",
            "name": "_value",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#property__value"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\BaseEnum\u003A\u003A\u0024_name",
            "name": "_name",
            "summary": "",
            "url": "classes/SteamSearch-Enums-BaseEnum.html#property__name"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice",
            "name": "MaxPrice",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AFree\u0028\u0029",
            "name": "Free",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_Free"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AFive\u0028\u0029",
            "name": "Five",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_Five"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003ATen\u0028\u0029",
            "name": "Ten",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_Ten"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AFifteen\u0028\u0029",
            "name": "Fifteen",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_Fifteen"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003ATwenty\u0028\u0029",
            "name": "Twenty",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_Twenty"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003ATwentyFive\u0028\u0029",
            "name": "TwentyFive",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_TwentyFive"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AThirty\u0028\u0029",
            "name": "Thirty",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_Thirty"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AThirtyFive\u0028\u0029",
            "name": "ThirtyFive",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_ThirtyFive"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AForty\u0028\u0029",
            "name": "Forty",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_Forty"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AFortyFive\u0028\u0029",
            "name": "FortyFive",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_FortyFive"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AFifty\u0028\u0029",
            "name": "Fifty",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_Fifty"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AFiftyFive\u0028\u0029",
            "name": "FiftyFive",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_FiftyFive"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003ASixty\u0028\u0029",
            "name": "Sixty",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_Sixty"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\MaxPrice\u003A\u003AAll\u0028\u0029",
            "name": "All",
            "summary": "",
            "url": "classes/SteamSearch-Enums-MaxPrice.html#method_All"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\SortBy",
            "name": "SortBy",
            "summary": "",
            "url": "classes/SteamSearch-Enums-SortBy.html"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\SortBy\u003A\u003ARelevance\u0028\u0029",
            "name": "Relevance",
            "summary": "",
            "url": "classes/SteamSearch-Enums-SortBy.html#method_Relevance"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\SortBy\u003A\u003AReleased\u0028\u0029",
            "name": "Released",
            "summary": "",
            "url": "classes/SteamSearch-Enums-SortBy.html#method_Released"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\SortBy\u003A\u003AName\u0028\u0029",
            "name": "Name",
            "summary": "",
            "url": "classes/SteamSearch-Enums-SortBy.html#method_Name"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\SortBy\u003A\u003APriceAsc\u0028\u0029",
            "name": "PriceAsc",
            "summary": "",
            "url": "classes/SteamSearch-Enums-SortBy.html#method_PriceAsc"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\SortBy\u003A\u003APriceDesc\u0028\u0029",
            "name": "PriceDesc",
            "summary": "",
            "url": "classes/SteamSearch-Enums-SortBy.html#method_PriceDesc"
        },                {
            "fqsen": "\\SteamSearch\\Enums\\SortBy\u003A\u003AReviews\u0028\u0029",
            "name": "Reviews",
            "summary": "",
            "url": "classes/SteamSearch-Enums-SortBy.html#method_Reviews"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport",
            "name": "VRSupport",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method___construct"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetVrOnly\u0028\u0029",
            "name": "setVrOnly",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setVrOnly"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetVrSupported\u0028\u0029",
            "name": "setVrSupported",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setVrSupported"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetValveIndex\u0028\u0029",
            "name": "setValveIndex",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setValveIndex"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetHtcVive\u0028\u0029",
            "name": "setHtcVive",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setHtcVive"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetOculusRift\u0028\u0029",
            "name": "setOculusRift",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setOculusRift"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetWindowsMixedReality\u0028\u0029",
            "name": "setWindowsMixedReality",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setWindowsMixedReality"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetTrackedMotionControllers\u0028\u0029",
            "name": "setTrackedMotionControllers",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setTrackedMotionControllers"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetGamepad\u0028\u0029",
            "name": "setGamepad",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setGamepad"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetKeyboardMouse\u0028\u0029",
            "name": "setKeyboardMouse",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setKeyboardMouse"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetSeated\u0028\u0029",
            "name": "setSeated",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setSeated"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetStanding\u0028\u0029",
            "name": "setStanding",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setStanding"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AsetRoomScale\u0028\u0029",
            "name": "setRoomScale",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_setRoomScale"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetVrOnly\u0028\u0029",
            "name": "getVrOnly",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getVrOnly"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetVrSupported\u0028\u0029",
            "name": "getVrSupported",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getVrSupported"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetValveIndex\u0028\u0029",
            "name": "getValveIndex",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getValveIndex"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetHtcVive\u0028\u0029",
            "name": "getHtcVive",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getHtcVive"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetOculusRift\u0028\u0029",
            "name": "getOculusRift",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getOculusRift"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetWindowsMixedReality\u0028\u0029",
            "name": "getWindowsMixedReality",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getWindowsMixedReality"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetTrackedMotionControllers\u0028\u0029",
            "name": "getTrackedMotionControllers",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getTrackedMotionControllers"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetGamepad\u0028\u0029",
            "name": "getGamepad",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getGamepad"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetKeyboardMouse\u0028\u0029",
            "name": "getKeyboardMouse",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getKeyboardMouse"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetSeated\u0028\u0029",
            "name": "getSeated",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getSeated"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetStanding\u0028\u0029",
            "name": "getStanding",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getStanding"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AgetRoomScale\u0028\u0029",
            "name": "getRoomScale",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_getRoomScale"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003AtoQueryString\u0028\u0029",
            "name": "toQueryString",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020this\u0020object\u0020or\u0020null\u0020if\u0020it\u0020is\u0020empty.",
            "url": "classes/SteamSearch-Models-VRSupport.html#method_toQueryString"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024vrOnly",
            "name": "vrOnly",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_vrOnly"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024vrSupported",
            "name": "vrSupported",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_vrSupported"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024valveIndex",
            "name": "valveIndex",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_valveIndex"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024htcVive",
            "name": "htcVive",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_htcVive"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024oculusRift",
            "name": "oculusRift",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_oculusRift"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024windowsMixedReality",
            "name": "windowsMixedReality",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_windowsMixedReality"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024trackedMotionControllers",
            "name": "trackedMotionControllers",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_trackedMotionControllers"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024gamepad",
            "name": "gamepad",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_gamepad"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024keyboardMouse",
            "name": "keyboardMouse",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_keyboardMouse"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024seated",
            "name": "seated",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_seated"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024standing",
            "name": "standing",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_standing"
        },                {
            "fqsen": "\\SteamSearch\\Models\\VRSupport\u003A\u003A\u0024roomScale",
            "name": "roomScale",
            "summary": "",
            "url": "classes/SteamSearch-Models-VRSupport.html#property_roomScale"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder",
            "name": "QueryBuilder",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#method___construct"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#method___toString"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020QueryBuilder\u0020instance.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_create"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Set\u0020the\u0020search\u0020term.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_search"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AsortByRelevance\u0028\u0029",
            "name": "sortByRelevance",
            "summary": "Default\u0020steam\u0020search\u0020sort\u0020order.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_sortByRelevance"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AsortByReleaseDate\u0028\u0029",
            "name": "sortByReleaseDate",
            "summary": "Sort\u0020by\u0020release\u0020date.\u0020Most\u0020recent\u0020results\u0020first.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_sortByReleaseDate"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AsortByName\u0028\u0029",
            "name": "sortByName",
            "summary": "Sort\u0020by\u0020name.\u0020Alphabetical\u0020order.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_sortByName"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AsortByPriceAscending\u0028\u0029",
            "name": "sortByPriceAscending",
            "summary": "Sort\u0020by\u0020price.\u0020Lowest\u0020price\u0020first.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_sortByPriceAscending"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AsortByPriceDescending\u0028\u0029",
            "name": "sortByPriceDescending",
            "summary": "Sort\u0020by\u0020price.\u0020Highest\u0020price\u0020first.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_sortByPriceDescending"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AsortByReviewScore\u0028\u0029",
            "name": "sortByReviewScore",
            "summary": "Sort\u0020by\u0020review\u0020score.\u0020Highest\u0020score\u0020first.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_sortByReviewScore"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrOnly\u0028\u0029",
            "name": "vrOnly",
            "summary": "Filter\u0020results\u0020to\u0020show\u0020titles\u0020that\u0020only\u0020support\u0020VR.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrOnly"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrSupported\u0028\u0029",
            "name": "vrSupported",
            "summary": "Filter\u0020results\u0020to\u0020show\u0020titles\u0020with\u0020VR\u0020support.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrSupported"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrValveIndex\u0028\u0029",
            "name": "vrValveIndex",
            "summary": "Filter\u0020results\u0020to\u0020show\u0020titles\u0020that\u0020support\u0020the\u0020Valve\u0020Index.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrValveIndex"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrHtcVive\u0028\u0029",
            "name": "vrHtcVive",
            "summary": "Filter\u0020results\u0020to\u0020show\u0020titles\u0020that\u0020support\u0020the\u0020HTC\u0020Vive.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrHtcVive"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrOculusRift\u0028\u0029",
            "name": "vrOculusRift",
            "summary": "Filter\u0020results\u0020to\u0020show\u0020titles\u0020that\u0020support\u0020the\u0020Oculus\u0020Rift.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrOculusRift"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrWindowsMixedReality\u0028\u0029",
            "name": "vrWindowsMixedReality",
            "summary": "Filter\u0020results\u0020to\u0020show\u0020titles\u0020that\u0020support\u0020Windows\u0020Mixed\u0020Reality.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrWindowsMixedReality"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrTrackedMotionControllers\u0028\u0029",
            "name": "vrTrackedMotionControllers",
            "summary": "Filter\u0020results\u0020to\u0020show\u0020titles\u0020that\u0020support\u0020tracked\u0020motion\u0020controllers.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrTrackedMotionControllers"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrGamepad\u0028\u0029",
            "name": "vrGamepad",
            "summary": "Filter\u0020results\u0020to\u0020show\u0020titles\u0020that\u0020support\u0020gamepads.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrGamepad"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrKeyboardMouse\u0028\u0029",
            "name": "vrKeyboardMouse",
            "summary": "Filter\u0020results\u0020to\u0020show\u0020titles\u0020that\u0020support\u0020keyboard\u0020and\u0020mouse.",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrKeyboardMouse"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrSeated\u0028\u0029",
            "name": "vrSeated",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrSeated"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrStanding\u0028\u0029",
            "name": "vrStanding",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrStanding"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AvrRoomScale\u0028\u0029",
            "name": "vrRoomScale",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#method_vrRoomScale"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003A\u0024maxPrice",
            "name": "maxPrice",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#property_maxPrice"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AgetTerm\u0028\u0029",
            "name": "getTerm",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#method_getTerm"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AgetSort\u0028\u0029",
            "name": "getSort",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#method_getSort"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003AgetMaxPrice\u0028\u0029",
            "name": "getMaxPrice",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#method_getMaxPrice"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003ASTEAM_SEARCH_URL",
            "name": "STEAM_SEARCH_URL",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#constant_STEAM_SEARCH_URL"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003A\u0024term",
            "name": "term",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#property_term"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003A\u0024sort",
            "name": "sort",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#property_sort"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003A\u0024vrSupport",
            "name": "vrSupport",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#property_vrSupport"
        },                {
            "fqsen": "\\SteamSearch\\QueryBuilder\u003A\u003A\u0024excludeVROnly",
            "name": "excludeVROnly",
            "summary": "",
            "url": "classes/SteamSearch-QueryBuilder.html#property_excludeVROnly"
        },                {
            "fqsen": "\\SteamSearch\\SearchResult",
            "name": "SearchResult",
            "summary": "",
            "url": "classes/SteamSearch-SearchResult.html"
        },                {
            "fqsen": "\\SteamSearch\\SearchResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SteamSearch-SearchResult.html#method___construct"
        },                {
            "fqsen": "\\SteamSearch\\SearchResult\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/SteamSearch-SearchResult.html#property_title"
        },                {
            "fqsen": "\\SteamSearch\\SearchResult\u003A\u003A\u0024appId",
            "name": "appId",
            "summary": "",
            "url": "classes/SteamSearch-SearchResult.html#property_appId"
        },                {
            "fqsen": "\\SteamSearch\\SearchResult\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/SteamSearch-SearchResult.html#property_url"
        },                {
            "fqsen": "\\SteamSearch\\SearchResult\u003A\u003A\u0024releaseDate",
            "name": "releaseDate",
            "summary": "",
            "url": "classes/SteamSearch-SearchResult.html#property_releaseDate"
        },                {
            "fqsen": "\\SteamSearch\\SearchResult\u003A\u003A\u0024reviewSummary",
            "name": "reviewSummary",
            "summary": "",
            "url": "classes/SteamSearch-SearchResult.html#property_reviewSummary"
        },                {
            "fqsen": "\\SteamSearch\\SteamSearch",
            "name": "SteamSearch",
            "summary": "",
            "url": "classes/SteamSearch-SteamSearch.html"
        },                {
            "fqsen": "\\SteamSearch\\SteamSearch\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SteamSearch-SteamSearch.html#method___construct"
        },                {
            "fqsen": "\\SteamSearch\\SteamSearch\u003A\u003ASearch\u0028\u0029",
            "name": "Search",
            "summary": "Perform\u0020a\u0020search\u0020on\u0020the\u0020Steam\u0020store\u0020using\u0020either\u0020a\u0020basic\u0020search\u0020string\u0020or\u0020a\u0020QueryBuilder\u0020with\u0020custom\u0020parameters.",
            "url": "classes/SteamSearch-SteamSearch.html#method_Search"
        },                {
            "fqsen": "\\SteamSearch\\SteamSearch\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/SteamSearch-SteamSearch.html#property_client"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\SteamSearch\\Enums",
            "name": "Enums",
            "summary": "",
            "url": "namespaces/steamsearch-enums.html"
        },                {
            "fqsen": "\\SteamSearch\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/steamsearch-models.html"
        },                {
            "fqsen": "\\SteamSearch",
            "name": "SteamSearch",
            "summary": "",
            "url": "namespaces/steamsearch.html"
        }            ]
);
