name: Generate PHP Documentation

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@1.8.2
        with:
          extensions: intl
          php-version: "8.1"
    
      - uses: actions/checkout@v2

      - name: Download phpDocumentor
        uses: wei/wget@v1.1.1
        with:
          args: https://phpdoc.org/phpDocumentor.phar
        
      - run: ls
        
      - name: Build the documentation
        run: php phpDocumentor.phar -d src -t docs --title "steam-search documentation"
        
      - name: Publish on GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
